<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.3790" tests="12" failures="10">
  <testsuite name="Root Suite" timestamp="2023-06-12T10:52:40" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="reminders_api" timestamp="2023-06-12T10:52:40" tests="12" file="/projects/challenge/test/index.spec.js" time="0.3790" failures="10">
    <testcase name="reminders_api should create a new reminder" time="0.0700" classname="should create a new reminder">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200
    at Context.<anonymous> (test/index.spec.js:57:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders" time="0.0460" classname="should fetch all the reminders">
    </testcase>
    <testcase name="reminders_api should fetch no reminders if no matching results are present for user" time="0.0330" classname="should fetch no reminders if no matching results are present for user">
      <failure message="expected [ Array(4) ] to deeply equal []" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal []
    at Context.<anonymous> (test/index.spec.js:73:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch no reminders if no matching results are present after the date" time="0.0300" classname="should fetch no reminders if no matching results are present after the date">
      <failure message="expected [ Array(4) ] to deeply equal []" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal []
    at Context.<anonymous> (test/index.spec.js:80:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders for a user" time="0.0290" classname="should fetch all the reminders for a user">
      <failure message="expected [ Array(4) ] to deeply equal [ Array(2) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal [ Array(2) ]
    at Context.<anonymous> (test/index.spec.js:87:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders after the date" time="0.0290" classname="should fetch all the reminders after the date">
      <failure message="expected [ Array(4) ] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:94:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders for a user after the date" time="0.0280" classname="should fetch all the reminders for a user after the date">
      <failure message="expected [ Array(4) ] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:101:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch a single reminder" time="0.0180" classname="should fetch a single reminder">
    </testcase>
    <testcase name="reminders_api should get 404 if the reminder ID does not exist" time="0.0150" classname="should get 404 if the reminder ID does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 200
    at Context.<anonymous> (test/index.spec.js:114:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a put request to /reminders/:id" time="0.0270" classname="should get 405 for a put request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 200
    at Context.<anonymous> (test/index.spec.js:122:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a patch request to /reminders/:id" time="0.0380" classname="should get 405 for a patch request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 200
    at Context.<anonymous> (test/index.spec.js:128:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a delete request to /reminders/:id" time="0.0160" classname="should get 405 for a delete request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 200
    at Context.<anonymous> (test/index.spec.js:134:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>